# Generated by Django 5.2.1 on 2025-05-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.proceso')),
            ],
        ),
    ]
