# Generated by Django 5.2.4 on 2025-07-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entidad",
            name="activa",
            field=models.BooleanField(default=False),
        ),
    ]
